services:
  db:
    image: postgres
    container_name: wellness-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: wellnessdatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: wellness-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  bkdend:
    build:
      context: ./wellness-api
    container_name: wellness-api
    restart: unless-stopped
    environment:
      DATABASE_HOST: db
      REDIS_URL: redis://redis:6379/1
      RAILS_ENV: development
    volumes:
      - ./wellness-api:/app
    ports:
      - "3000:3000"
    command: bash -c "bundle exec rails db:prepare && bundle exec rails db:seed && exec bin/rails server -b 0.0.0.0"

  wellness-ui:
    build:
      context: ./wellness-ui
    container_name: wellness-ui
    depends_on:
      - bkdend
    # environment:
    #   VITE_API_URL: http://localhost:3000
    #   VITE_WS_URL: ws://localhost:3000/cable
    volumes:
      - ./wellness-ui:/app
    ports:
      - "5173:5173"
    command: ["serve", "-s", "dist", "-l", "5173"]

volumes:
  pgdata: